server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;

    location /data/ {
        proxy_pass http://ultrafeeder/data/;
        proxy_set_header Host ultrafeeder;
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
